# Generated by Django 5.2 on 2026-01-17 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("running", "跑步"),
                            ("swimming", "游泳"),
                            ("cycling", "骑行"),
                            ("walking", "散步"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.IntegerField(help_text="单位: 分钟")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女")],
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
                (
                    "height",
                    models.FloatField(help_text="单位: cm", verbose_name="身高"),
                ),
                (
                    "weight",
                    models.FloatField(help_text="单位: kg", verbose_name="体重"),
                ),
                ("birth_date", models.DateField(verbose_name="出生日期")),
                (
                    "activity_level",
                    models.FloatField(
                        choices=[
                            (1.2, "久坐 (几乎不运动)"),
                            (1.375, "轻度活跃 (每周运动 1-3 次)"),
                            (1.55, "中度活跃 (每周运动 3-5 次)"),
                            (1.725, "非常活跃 (每周运动 6-7 次)"),
                            (1.9, "超级活跃 (体力工作/专业运动员)"),
                        ],
                        default=1.2,
                        verbose_name="日常活动系数",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
