# Generated by Django 5.2 on 2026-01-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciselog",
            name="duration_minutes",
            field=models.IntegerField(help_text="単位: 分"),
        ),
        migrations.AlterField(
            model_name="exerciselog",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("running", "ランニング"),
                    ("swimming", "水泳"),
                    ("cycling", "サイクリング"),
                    ("walking", "ウォーキング"),
                    ("yoga", "ヨガ"),
                    ("weightlifting", "筋トレ"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.FloatField(
                choices=[
                    (1.2, "座り仕事が多い(運動なし)"),
                    (1.375, "軽い運動(週1-3回)"),
                    (1.55, "中程度の運動(週3-5回)"),
                    (1.725, "活発な運動(週6-7回)"),
                ],
                default=1.2,
                verbose_name="活動レベル",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(verbose_name="生年月日"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "男性"), ("F", "女性")],
                max_length=1,
                verbose_name="性別",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(help_text="単位: cm", verbose_name="身長"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(help_text="単位: kg", verbose_name="体重"),
        ),
    ]
